### ISSUE TITLE
Visual Studio 19 Exception

### ISSUE THREAD

**Issue by PrismElixir** [kaby76/AntlrVSIX#31] opened 2020-03-24 15:48 UTC
Opened Visual Studio.
Opened my Console application.
Opened my Grammar file (BMx.g4)
I added a single character to my grammar, and Visual Studio captured an exception.  See screenshot (attached).
I also have attached the LogFile mentioned in the Screenshot (also attached).  It is probably the the last error in this Log.  

Hope this helps. 

[ActivityLog.zip](https://github.com/kaby76/AntlrVSIX/files/4376218/ActivityLog.zip)

![VS2019_AntlrVsix_Error](https://user-images.githubusercontent.com/30986578/77446105-5082fa00-6dc4-11ea-9ddb-1eb084900b95.png)

**Comment by kaby76** [comment] 2020-03-24 18:15
Thanks, I'm aware of the problem, but not quite sure how to solve it. The problem is the order of updating to the LSP server with changes vs. asking for tagging information from the server. It needs to update the server first, then ask for tags, but it does this in the reverse, which completely messes up things, causing exceptions until the updates are written to the server. I thought I put in try/catches for all this stuff, but I need to add more. Thanks. -Ken

**Comment by kaby76** [comment] 2020-03-31 19:45
I'm going to close this bug for now. The LA set computation is still broken, but as long as you keep this off in the options (which is the default in version 5.8 of the extension), then you shouldn't see the exception. It'll also be more responsive since it's not doing a full exploration of the entire parse space up to the cursor. The LA sets will need to be computed another way.

**Closed by kaby76** 2020-03-31 19:45 UTC
